### ISSUE TITLE
Diamonds shards from Silent Gears turn into inventory Pets version nuggets after taking them out of the crafting grid

### ISSUE THREAD

**Issue by Veggetossj** [Diversion98/The-MHG-Modpack#1]
When attempting to craft diamond shards from Silent Gears, neccesary as part for the Material Grader, They come out as the Inventory Pets diamond nuggets instead. Tried this via Crafting Grid from Refined Storage and Crafting Station from Crafting Station mod. Normal crafting via player inventory or vanilla crafting bench doesnt even allow the selection of diamond shards

**Comment by Diversion98** [comment]
This if fixed in version 0.0.6e.

The normal recipe for the diamond nugget is gone but there is an alternate recipe.
