### ISSUE TITLE
ma sulfur essence useless

### ISSUE THREAD

**Issue by bobcatfish9** [Diversion98/The-MHG-Modpack#10]
**Describe the bug**
sulfur essence from mystical agriculture has no use, no way to create sulfur from it.

**Modpack Version**
0.1.5.1

**To Reproduce**
craft sulfur seeds
grow
harvest
try to craft sulfur

**Expected behavior**
sulfur from thermal series

**Comment by Diversion98** [comment]
This has been fixed in 1.6 and on the current official server
