### ISSUE TITLE
Insanium Reprocessor info crash

### ISSUE THREAD

**Issue by bobcatfish9** [Diversion98/The-MHG-Modpack#11]
**Describe the bug**
I don't know if only the Insanium Reprocessor or all below it do this. crash when pressing shift over item in inventory.

**Modpack Version**
0.1.5.1

**OS/Specs**
Windows 10 64 bit
RTX 2070 SUPER
Ryzen 7 3700X
32GB Ram

**To Reproduce**
1. work through seed reprocessor quest line
2. have Insanium Reprocessor Block in hotbar
3. hold shift over the item to show additional information
4. crash

**Expected behavior**
no crash, and show me additional info

**Crash Report or Logs**
https://paste.ee/p/ohJLu

**Comment by Diversion98** [comment]
This is allready fixed in 1.6 :)
