### ISSUE TITLE
AE2 Recipies

### ISSUE THREAD

**Issue by Krutontar** [Diversion98/The-MHG-Modpack#3]
There are a few odd recipes that AE2 doesn't want to register.  So far I've found Spruce Planks from a log and the recipe for netherite ingots.  The recipes are in the ME Interfaces but when I type the names in a grid it doesnt show up as a craftable option and if try to craft something that calls for those it says I don't have them.

**Comment by Krutontar** [comment]
I can't even shift click them from JEI to just craft in the grid.  I have to manually populate the grid.

**Comment by Diversion98** [comment]
Can confirm that this is with multiple recipes.

I also tried block of gold and block of steel and neither of them works.

**Comment by Krutontar** [comment]
Weirder, neither the vanilla netherite ingot recipe will work nor the mystical agriculture recipe.

**Comment by Diversion98** [comment]
Fixed with the next version.
