### ISSUE TITLE
quest 'first bit of steel' unobtainable

### ISSUE THREAD

**Issue by bobcatfish9** [Diversion98/The-MHG-Modpack#6]
**Describe the bug**
I am unable to complete 'first bit of steel' quest. The steel you get from the IE crude blast furnace is from silent mechanism and is not detected by quest book.

**Modpack Version**
0.1.5.1

**To Reproduce**
1. build immersive engineering crude blast furnace
2. burn iron into steel
3. receive incorrect steel for quest

**Expected behavior**
IE steel from IE crude blast furnace

**Comment by Diversion98** [comment]
Has been fixed on the server and will be fixed in 0.1.5.2/0.1.6.0
