### ISSUE TITLE
Invar recipes in Induction Smelter (Thermal) uses gold instead of iron.

### ISSUE THREAD

**Issue by Veggetossj** [Diversion98/The-MHG-Modpack#7]
**Describe the bug**
Induction Smelter recipe for Invar Ingots is 1 gold dust and 1 nickel dust, while Thermal by default has this set to 2 iron and 1 nickel for 3 invar, unsure if intentional thats its now gold?

**Modpack Version**
0.1.5.1

**OS/Specs**
Windows 10 64 bit
RTX 3060
I7-4790k
16GB Ram

**To Reproduce**
Check JEI for the recipe of an Invar Ingot. The Alloy Smelter from Silent Mechanisms shows the old recipe, while the Induction Smelter from Thermal shows a changed recipe of gold and nickel.

**Expected behavior**
The recipe is wrong.

**Crash Report or Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/3329975/159114560-45b94717-3867-4498-9124-a015e6493721.png)

**Comment by Diversion98** [comment]
fixed in 1.6 and on the server :)
