### ISSUE TITLE
Block of Lead not showing in Compacting Drawer/ BoL has multiple crafting recipes.

### ISSUE THREAD

**Issue by Veggetossj** [Diversion98/The-MHG-Modpack#8]
**Describe the bug**
When putting lead ingot/nuggets into a compacting drawer, the top place, usually where blocks show, doesnt appear, instead the ingot takes the top spot.
Unsure if this is related to lead still have 3 seperate recipes for a block of lead?

**Modpack Version**
0.1.5.1

**OS/Specs**
Windows 10 64 bit
RTX 3060
I7-4790k
16GB Ram

**To Reproduce**
Grab 9+ lead ingot and put them in a compacting hopper, top slot will show ingots not a block.

Furthermore with trying to creaft a block fo lead, 3 options appear.

**Expected behavior**
Top slot in the drawer should show a lead block when more then 9 ingot are stored in it.

**Screenshots**
![image](https://user-images.githubusercontent.com/3329975/159784024-20140fd9-e0a2-48db-989c-a90028957a88.png)
![image](https://user-images.githubusercontent.com/3329975/159784188-594f218c-80d8-4179-ae63-1c8bb9f7ca19.png)

**Comment by Diversion98** [comment]
oops never did lead blocks xD
will fix tomorrow on the server :)

**Comment by Diversion98** [comment]
this has been fixed in 1.6 and on the server :)
