### ISSUE TITLE
Signalum Ingot recipe in Induction Smelter incorrect

### ISSUE THREAD

**Issue by Veggetossj** [Diversion98/The-MHG-Modpack#9]
**Describe the bug**
The recipe for Signalum Ingot is incorrect in the Induction Smelter of Thermal. by default the recipe is 3 copper + 1 silver + 10 redstone = 4 Signalum

**Modpack Version**
0.1.5.1

**OS/Specs**
Windows 10 64 bit
RTX 3060
I7-4790k
16GB Ram

**To Reproduce**
Compare recipes from the Silent Mechanisms Alloy Smelter (correct one) to the one in the Induction Smelter (incoorrect one)

**Expected behavior**
Recipes should be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/3329975/161388044-0f113925-89e2-4f11-bdd3-3b017dac228e.png)
![image](https://user-images.githubusercontent.com/3329975/161388056-4b34b004-34ac-4331-a864-5ae9280e7b93.png)

**Comment by Diversion98** [comment]
will be fixed in 0.1.6 and is allready fixed on the server :)
